# Generated by Django 4.1.7 on 2023-06-20 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('is_multiple_choice', models.BooleanField(default=False)),
                ('is_free_text', models.BooleanField(default=False)),
                ('a', models.CharField(max_length=300)),
                ('b', models.CharField(max_length=300)),
                ('c', models.CharField(max_length=300)),
                ('d', models.CharField(max_length=300)),
                ('correct', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=8000)),
                ('id_in_exam', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exam')),
            ],
        ),
    ]
